// Generated by scripts/generate-worker-redirects.mjs — do not edit by hand.
export const REDIRECTS: Record<string, string> = {
  "clippy": "https://clippy.smashit.tw",
  "fastgoto": "https://fastgoto.xyz"
};
